on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: License project CI/CD
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: license-repo
          region: eu-west-1
          tags: latest,${{ github.sha }}
          create_repo: true